export const MEME_CAPTIONS = [
  "When you realize it's Monday tomorrow…",
  "That moment when you thought you were done, but you're not.",
  "Me trying to be productive but getting distracted by literally everything.",
  "How it started vs. How it's going.",
  "When your plan doesn't go as planned.",
  "Me: 'I'll just check one thing.' Also me: 3 hours later…",
  "When you hear someone call your name but you're home alone.",
  "Me pretending to be surprised when I knew the whole time.",
  "When you're too tired to function but still have responsibilities.",
  "That face you make when someone asks a dumb question.",
  "Me: 'I'm going to bed early tonight.' Also me at 2 AM:",
  "When the WiFi goes out and you have to use your data.",
  "When you finally understand a joke from 3 years ago.",
  "When you try to adult but immediately regret it.",
  "Me after saying 'I'll do it tomorrow' for the fifth day in a row.",
  "When you accidentally like their photo from 3 years ago.",
  "When the teacher asks if you're paying attention.",
  "Me trying to explain something without actually knowing what I'm talking about.",
  "When you're trying to stay positive but life keeps testing you.",
  "When you've already asked 'What?' twice, so you just smile and nod.",
  "Me trying to be healthy but then someone mentions pizza.",
  "When you're trying to be mad but then they make you laugh.",
  "Me: 'I'm not dramatic.' Also me:",
  "When you're trying to be mad but then they make you laugh.",
];
