import { Caption } from "@/types/memeAlchemy";

export const MEME_CAPTIONS: Caption[] = [
  { id: 'C_1', top: "When you realize it's Monday tomorrow…" },
  { id: 'C_2', top: "That moment when you thought you were done, but you're not." },
  { id: 'C_3', top: "Me trying to be productive but getting distracted by literally everything." },
  { id: 'C_4', top: "How it started vs. How it's going." },
  { id: 'C_5', top: "When your plan doesn't go as planned." },
  { id: 'C_6', top: "Me: 'I'll just check one thing.' Also me: 3 hours later…" },
  { id: 'C_7', top: "When you hear someone call your name but you're home alone." },
  { id: 'C_8', top: "Me pretending to be surprised when I knew the whole time." },
  { id: 'C_9', top: "When you're too tired to function but still have responsibilities." },
  { id: 'C_10', top: "That face you make when someone asks a dumb question." },
  { id: 'C_11', top: "Me: 'I'm going to bed early tonight.' Also me at 2 AM:" },
  { id: 'C_12', top: "When the WiFi goes out and you have to use your data." },
  { id: 'C_13', top: "When you finally understand a joke from 3 years ago." },
  { id: 'C_14', top: "When you try to adult but immediately regret it." },
  { id: 'C_15', top: "Me after saying 'I'll do it tomorrow' for the fifth day in a row." },
  { id: 'C_16', top: "When you accidentally like their photo from 3 years ago." },
  { id: 'C_17', top: "When the teacher asks if you're paying attention." },
  { id: 'C_18', top: "Me trying to explain something without actually knowing what I'm talking about." },
  { id: 'C_19', top: "When you're trying to stay positive but life keeps testing you." },
  { id: 'C_20', top: "When you've already asked 'What?' twice, so you just smile and nod." },
  { id: 'C_21', top: "Me trying to be healthy but then someone mentions pizza." },
  { id: 'C_22', top: "When you're trying to be mad but then they make you laugh." },
  { id: 'C_23', top: "Me: 'I'm not dramatic.' Also me:" },
  { id: 'C_24', top: "When you're trying to be mad but then they make you laugh." },
];
